spring:
  datasource:
#    url: jdbc:h2:mem:dati;DATABASE_TO_UPPER=false;QUERY_TIMEOUT=30
    url: jdbc:h2:file:${user.dir}/db/dati;QUERY_TIMEOUT=30;mode=mysql
    username: root
    password: dca
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console/dati
      enabled: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic  # 如果有认证
    password: yimin123
    connection-timeout: 5s
    socket-timeout: 30s

dati:
  mcp:
    endpoint-base-url: http://localhost:${server.port}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
#logging:
#  level:
#    # 核心：打印es 交互信息
#    org.apache.http.wire: DEBUG