/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/datasources/': RouteRecordInfo<
      '/datasources/',
      '/datasources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/datasources/[id]/tables/': RouteRecordInfo<
      '/datasources/[id]/tables/',
      '/datasources/:id/tables',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/datasources/[id]/tables/[tableId]/columns': RouteRecordInfo<
      '/datasources/[id]/tables/[tableId]/columns',
      '/datasources/:id/tables/:tableId/columns',
      { id: ParamValue<true>, tableId: ParamValue<true> },
      { id: ParamValue<false>, tableId: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mcp-services/': RouteRecordInfo<
      '/mcp-services/',
      '/mcp-services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mcp-services/[id]/': RouteRecordInfo<
      '/mcp-services/[id]/',
      '/mcp-services/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subjects/': RouteRecordInfo<
      '/subjects/',
      '/subjects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/subjects/[id]': RouteRecordInfo<
      '/subjects/[id]',
      '/subjects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/datasources/index.vue': {
      routes:
        | '/datasources/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/datasources/[id]/tables/index.vue': {
      routes:
        | '/datasources/[id]/tables/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/datasources/[id]/tables/[tableId]/columns.vue': {
      routes:
        | '/datasources/[id]/tables/[tableId]/columns'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mcp-services/index.vue': {
      routes:
        | '/mcp-services/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mcp-services/[id]/index.vue': {
      routes:
        | '/mcp-services/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subjects/index.vue': {
      routes:
        | '/subjects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/subjects/[id].vue': {
      routes:
        | '/subjects/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
