/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/datasources/': RouteRecordInfo<'/datasources/', '/datasources', Record<never, never>, Record<never, never>>,
    '/datasources/[id]/tables/': RouteRecordInfo<'/datasources/[id]/tables/', '/datasources/:id/tables', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/datasources/[id]/tables/[tableId]/columns': RouteRecordInfo<'/datasources/[id]/tables/[tableId]/columns', '/datasources/:id/tables/:tableId/columns', { id: ParamValue<true>, tableId: ParamValue<true> }, { id: ParamValue<false>, tableId: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/subjects/': RouteRecordInfo<'/subjects/', '/subjects', Record<never, never>, Record<never, never>>,
    '/subjects/[id]': RouteRecordInfo<'/subjects/[id]', '/subjects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/datasources/index.vue': {
      routes: '/datasources/'
      views: never
    }
    'src/pages/datasources/[id]/tables/index.vue': {
      routes: '/datasources/[id]/tables/'
      views: never
    }
    'src/pages/datasources/[id]/tables/[tableId]/columns.vue': {
      routes: '/datasources/[id]/tables/[tableId]/columns'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/subjects/index.vue': {
      routes: '/subjects/'
      views: never
    }
    'src/pages/subjects/[id].vue': {
      routes: '/subjects/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
