spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:dataconnai;DATABASE_TO_UPPER=false;QUERY_TIMEOUT=30
    url: jdbc:h2:file:${user.dir}/IdeaProjects/dati/db/dataconnai;QUERY_TIMEOUT=30;mode=mysql
    username: root
    password: dca
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console/dataconnai
      enabled: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic  # 如果有认证
    password: yimin123
    connection-timeout: 5s
    socket-timeout: 30s
  data:
    elasticsearch:
      repositories:
        enabled: true