server:
  port: 8085

spring:
  application:
    name: DatI
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    property-naming-strategy: SNAKE_CASE
