system:
  column-value-sample-limit: 1000
  column-value-length-limit: 256

server:
  port: 8085

spring:
  application:
    name: DatI
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    property-naming-strategy: SNAKE_CASE

auth:
  admin-users: ${ADMIN_USERS:admin}
  jwt:
    secret: ${JWT_SECRET:this-is-a-32-char-long-default-secret-key}
    expiration-seconds: 604800
